services:
  mongo:
    image: mongo:6.0
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo_admin
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    environment:
      MONGO_USER: mongo_admin
      MONGO_PASS: password
      MONGO_HOST: mongo
      MONGO_PORT: 27017

volumes:
  mongo_data:
